### ISSUE TITLE
More understanding on how it works

### ISSUE THREAD

**Issue by YouhannaSabry1** [daveagp/java_visualize#7]
@daveagp 
I am trying to develop this project more for my thesis and for enhancing education purposes, if you'd please explain how the code works and how the execution is made. it would be a great help.
Thanks in advance.

**Comment by daveagp** [comment]
It will be better if you make your own attempt to understand the code I think and I do not have time to provide a comprehensive overview. But if you have specific questions about specific pieces that you've read, it should be possible for me to answer those questions (though I may not be able to respond quickly).
